# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

u = User.create(name: "John Muir", email: "jmuir@gmail.com", password: "password")
th = Trailhead.create(name: "Angels Rest Trailhead", location: "Lat. 45.56065, Long. -122.17241", amenities: "Small parking lot, no restrooms, open for day-use 6:00 AM - 10:00 PM.", fees: "No fees or permits required.")

h = Hike.create(name: "Angels Rest Hike", difficulty: "Moderate", distance: "4.8 miles round-trip", elevation_gain: "1475 feet", hike_type: "Out and Back", description: "Angels Rest is an exposed bluff on the western end of the Columbia River Gorge. The platy andesite that composes this promontory is part of a million-year-old lava flow from Larch Mountain, a member of the Boring Lava Field. The summit is characterized by a long, rocky spine surrounded on three sides by cliffs, boasting a striking 270 degree view! While you can't see any of the Cascade volcanoes from the top, you do get great vantages of Beacon Rock, Silver Star Mountain and many other landmarks. The real draw, however, is the perspective of the Columbia River below - like you're on a balcony over a great auditorium. Its 1500 foot prominence and its proximity to the Columbia River give you the false sensation that you could dive from Angels Rest to the water below!

    Getting to this precipice takes a relatively short hike (2.4 miles one-way) with an easy to moderately-steep ascent. Its bang-for-the-buck makes this a long-time favorite of families and hiking clubs. When you consider that the drive time from downtown Portland to the trailhead is under 45 minutes, it is understandable how popular this destination can be on weekends throughout the year. The trail passes two waterfalls along the way, an overhead view of Coopey Falls and a quick detour to smaller Upper Coopey Falls. The forest expanses surrounding the summit burned in the Multnomah Falls Fire back in 1991, while the 2017 Eagle Creek Fire burned over most of the trail's route. Much of the latter was a ground fire that cleared out the understory, which is fast regenerating. Where the two fires overlapped, vistas have opened up and blackened snags sprout from the steep slopes. However, during the wet season, parts of the trail can get muddy and slick. It is a unique landscape - one quite varied from other locales in the Gorge. For a longer loop that gives you more elevation, see the Angels Rest-Devils Rest Loop Hike.
    
    There are two parking areas, one above the other at the Bridal Veil intersection on the Historic Columbia River Highway. The trails from each converge just above the lower parking area. Hike up a forested slope where the bases of large Douglas-firs bear scorch marks from the 2017 fire. Vine maple, thimbleberry, and sword fern form the understory, and occasionally there are patches of poison oak. Cross an open talus slope to get views to down to sheep paddocks below, the Columbia River, Phoca Rock, Cape Horn, the Prindle Cliffs, and Silver Star Mountain. A clifftop viewpoint gives you a look down to 150-foot Coopey Falls, which spills down to property owned by the Franciscan Sisters of the Eucharist. Hiking up, you'll see a short spur leading left to get a view up the creek of Upper Coopey Falls. The trail leads up through a hazel thicket, and another spur takes you to the base of the upper tier of Upper Coopey Falls. Continue up under alders and maples to cross Coopey Creek on a footbridge.
    
    The trail turns at a reinforced switchback, and then traverses up a slope of maples to switchback again and head out to the Gorge face, where you'll encounter brushier terrain recovering from the 1991 burn. Views are more open now, and you can see up to the cliffs of Angels Rest as well as the entire profile of Washington's Larch Mountain and Silver Star Mountain to the north. Switchback twice, and get another view of Silver Star Mountain from a viewpoint at a section of split-rail fencing. Switchback twice more to get a view of the keyhole or \"eye\" at the point of Angels Rest. Four more switchbacks take you higher in a scrubby landscape of snowberry, ocean spray, and 1991 fire snags seared black by the 2017 fire. Three short switchbacks take you to a talus slope traverse, after which the trail enters a dense thicket and then switchbacks up to a junction at the crest of the Angels Rest promontory.
    
    Go left here to head out to the point. You will scramble among layered pillars of platy andesite getting views down to the Columbia River as well as west to Sand Island and the tall buildings of downtown Portland. To the north, Larch Mountain and Silver Star Mountain in Washington are on the skyline, while an expanse of the Washington Gorge, from Cape Horn to Hamilton Mountain and Beacon Rock, is on display. Scrubby alders and few stunted oaks survive up here, and the east wind can be extremely fierce on certain fall and winter days.
    
    Note for families: While there is plenty of space to avoid danger at the top, keep little ones close and away from the cliffside drop-offs. As one somewhat nervous woman pointed out \"There are no handrails\".", family_friendly: true, user_id: u.id, trailhead_id: th.id)


Hike.create(name: "Angels Rest-Devils Rest Loop", difficulty: "Moderate", distance: "10.8 miles", elevation_gain: "3040 feet", hike_type: "Loop", description: "The lollipop loop from Angels Rest to Devils Rest encapsulates a variety of experiences at this western end of the Columbia River Gorge. Angels Rest indeed offers heavenly vistas from its exposed promontory 1,500 feet above the Columbia River. Devils Rest, ironically 900 feet above Angels Rest, offers no views whatsoever at its mossy rock summit although there are commanding views east from clifftop perches nearby. The two destinations do have something in common, however, as both are manifestations of the Boring Lava Field, only a million or so years old compared to the 15 million-year-old Columbia River Basalt flows. Angels Rest is an andesite lava flow from Larch Mountain, while Devils Rest is one of the 99 Boring volcanoes. Most of the area you will be traveling through was affected by two recent fires. The 1991 Multnomah Falls Fire scorched the slopes between Angels Rest and Multnomah Falls; the 2017 Eagle Creek Fire was more extensive, but your descent from Devils Rest will be on user-maintained unofficial trails that were undamaged or little damaged by that blaze. Throw in a couple of waterfalls and gushing Wahkeena Spring, and this loop offers an eminently satisfying outing.

    There are two parking areas, one above the other at the Bridal Veil intersection on the Historic Columbia River Highway. The trails from each converge just above the lower parking area. Hike up a forested slope where the bases of large Douglas-firs bear scorch marks from the 2017 fire. Vine maple, thimbleberry, and sword fern form the understory, and occasionally there are patches of poison oak. Cross an open talus slope to get views to down to sheep paddocks below, the Columbia River, Phoca Rock, Cape Horn, the Prindle Cliffs, and Silver Star Mountain. A clifftop viewpoint gives you a look down to 150-foot Coopey Falls, which spills down to property owned by the Franciscan Sisters of the Eucharist. Hiking up, you'll see a short spur leading left to get a view up the creek of Upper Coopey Falls. The trail leads up through a hazel thicket, and another spur takes you to the base of the upper tier of Upper Coopey Falls. Continue up under alders and maples to cross Coopey Creek on a footbridge.
    
    The trail turns at a reinforced switchback, and then traverses up a slope of maples to switchback again and head out to the Gorge face, where you'll encounter brushier terrain recovering from the 1991 and 2017 fires. Views are more open now, and you can see up to the cliffs of Angels Rest as well as the entire profile of Washington's Larch Mountain and Silver Star Mountain to the north. Switchback twice, and get another view of Silver Star Mountain from a viewpoint at a section of split-rail fencing. Switchback twice more to get a look up to the keyhole or \"eye\" at the point of Angels Rest. Four more switchbacks take you higher in a scrubby landscape of snowberry, ocean spray, and 1991 fire snags seared black by the 2017 fire. An additional three short switchbacks convey you to a talus slope traverse, after which the trail enters a dense thicket and then switchbacks up to a junction at the crest of the Angels Rest promontory.
    
    Go left here to head out to the point. You will scramble among layered pillars of platy andesite getting views down to the Columbia River as well as west to Sand Island and the tall buildings of downtown Portland. To the north, Larch Mountain and Silver Star Mountain in Washington are on the skyline, while an expanse of the Washington Gorge, from Cape Horn to Hamilton Mountain and Beacon Rock, is on display. Scrubby alders and few stunted oaks survive up here, and the east wind can be extremely fierce on certain fall and winter days.
    
    Return along the ridge crest, and proceed beyond the junction with the spur trail to continue on the Angels Rest Trail #415. After a couple of switchbacks and more good views, you'll come to the unmarked junction with Foxglove Way, your return point. From this area of crown fire, there's a good view down the spine of the Angels Rest promontory to the Columbia River. Continue east on the Angels Rest Trail, which drops above the Dalton Creek bowl through a fast recovering carpet of Oregon grape, phacelia, snowberry, and bracken. Pass below an andesite talus slope, and then rise to a lovely intact grove of old-growth Douglas-fir, hemlock, and western red-cedar at a creek crossing. The trail gradually ascends through more scorched conifers and then passes through a thicket of young maples and bracken to enter a soggy Sitka alder bowl with numerous seeps. Hike through a grove of large red alders, and soon pass the almost unnoticeable Angels Rest-Foxglove Way Trail East Junction. Descending from here, you'll cross the Mist Creek Footbridge on a slightly blackened log and switchback down getting views down to the Wahkeena Bowl with most of its green canopy intact. Pass through a thimbleberry thicket, and make five more descending switchbacks to traverse out of the crown fire zone. At a break in the trees, you can get a view across the river to Archer Mountain, the only place on the Washington side of the Columbia that was affected by the Eagle Creek Fire. As you cross a rocky outcrop, you'll hear a large spring gushing forth below the trail. Round a corner, and catch a glimpse down to Fairy Falls across tumbling Wahkeena Creek. The trail rises to give you more views of cascading Wahkeena Creek. Reach a lovely cedar bench, and pass above gushing Wahkeena Spring to reach the Wahkeena-Angels Rest Trail Junction.
    
    Keep right, and hike up a slope of good-sized Douglas-firs and hemlocks with a delicate carpet of oxalis and inside-out flower. Pass a Wahkeena Trail sign being eaten by a tree. You'll arrive at the first of two junctions 25 yards apart. Stay right at both junctions, and find yourself ascending the Devils Rest Trail #420C.
    
    Make six switchbacks up along Shady Creek to reach a shallow bowl of large Douglas-firs and hemlocks. At a break in the trees, you'll get a view over to the prominence of Devils Rest. Hike along the rim of the Wahkeena Bowl, getting views of the cliff faces and scree slopes below Devils Rest. Pass the junction with a short spur that leads out to gated Multnomah Basin Road. Western hemlocks dominate the forest on this rim, and you'll pass through a grove that didn't even experience a ground burn. The forest opens up for a view north to Silver Star Mountain. Drop to cross two footbridges below a set of springs, and hike up through a thicket of devil's club. A spur trail leads right for a clifftop view west towards Yeon Mountain on the Oregon side of the Gorge and Hamilton Mountain and Table Mountain on the Washington side. Back on the main trail, drop and rise to look for a faint user trail just after an obvious survey marker. The side trail leads to a pinnacled clifftop promontory with extensive views including Mount Saint Helens, Mount Rainier, Mount Adams, Skamania Island and the Washington side of the Columbia River Gorge. The main Devils Rest Trail veers left, and then rises steeply from an old logging road to a trail junction. Go right here to the largely unburned summit of Devils Rest with its mossy arrangement of boulders. Just east of the boulders, the old course of the Primrose Path descends steeply to the Angels Rest Trail just east of the Mist Creek Footbridge.
    
    To complete the loop, however, you'll be continuing on the trail that leads down from the junction below Devils Rest. Drop through an unburned stand of Douglas-fir to reach a logging track shaded by alders. Then return to a coniferous wood with a sword fern understory and keep dropping steeply, with same-aged hemlocks to the left and a dense corridor of alder and young hemlock to your right. Reach a junction of makeshift signs in a salmonberry thicket on an old logging road. Keep left here for Angels Rest. The route rises steadily on an abandoned logging track. At a road junction, make a sharp right following Angels Rest and Foxglove Trail signs, and begin descending under alders and Douglas-firs along an edge of the Eagle Creek Burn. Vine maple and sword fern dominate in the understory. Salmonberry encroaches on the trail, but the path is regularly maintained by volunteers. Come to a junction with several signs for Foxglove Way, and go left. Make a level traverse through mature Douglas-fir forest with mossy vine maples, some lightly burned, overhanging the trail. Drop down the nose of a ridge through a dense thicket and arrive at the Angels Rest-Foxglove Way Trail West Junction. Make a left to return down the Angels Rest Trail to your vehicle.
    
    ", family_friendly: true, wildflowers: true, user_id: u.id, trailhead_id: th.id)

CheckIn.create(user_id: u.id, trailhead_id: th.id, check_in_date: Date.today)

TripReport.create(user_id: u.id, hike_id: h.id, trip_report_date: Date.today, rating: 5, content: "Gorgeous day on the gorge, windy of course! Got there as soon as the trailhead opened at 6:00 AM and enjoyed the trail and views at Angels Rest to myself, didn't see any other hikers until last 30 min going back to the parking lot. By the time I was leaving at about 8:45 AM, the lot was about half full. Trail in good conidition despite the heavy rain we've been having!")